server:
  port: 8002
  
spring:
  application:
    name: cloud-client
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/